volumes:
  caddy_data:
  caddy_config:
  frontend_dist:

services:
  backend:
    environment:
      - "API_ROOT_PREFIX=/api"

  frontend:
    environment:
      - "VITE_API=http://production_domain/api"
    command: "bun run build"
    volumes:
      - frontend_dist:/app/dist/

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - frontend_dist:/app/dist/
      - caddy_data:/data
      - caddy_config:/config
